### ISSUE TITLE
Add Selection/Deselection of One or Multiple Projects

### ISSUE THREAD

**Issue by ChocolateNao** [kvart714/nx-filter#1]
## Description

Since neither the community nor the nrwl team themselves [doesn't seem to make an attempt](https://github.com/nrwl/nx-console/issues/1970) on adding similar functionality to Nx Console, I took a liking of this project and would like to suggest a small UX improvement such as the ability to quickly select/deselect projects that are to be hidden

## Motivation

As the project grows larger (especially in a monorepo), it becomes annoying to click all the checkboxes to make, for example, only one app visible.

## Suggested Implementation

This could be a set of buttons which are located near to the `Refresh` button or make buttons appear when hovering over an element e.g. library, which in my opinion is preferable.

**Comment by kvart714** [comment]
@ChocolateNao done.
new version will appear on the marketplace soon
